name: Build and Release Avalonia Application

on:
  push:
    branches:
      - master # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.414 # Specify a different version here

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Avalonia application
        run: dotnet build --configuration Release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.414 # Update to your desired .NET version

      - name: Publish Avalonia application
        run: dotnet publish -c Release -r win-x64 -o ./publish

      - name: Set up Git
        run: git config --global user.email "saiganesh7989@github.com" && git config --global user.name "Gani-23"

      - name: Create Git Tag
        run: git tag -a v${{ github.run_number }} -m "Version v${{ github.run_number }}"

      - name: Push Git Tag
        run: git push origin v${{ github.run_number }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.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 }} # Replace with the name of your GitHub PAT secret
